// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jakdsjslactlnullqtec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impha2RzanNsYWN0bG51bGxxdGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDU0NjksImV4cCI6MjA3MTc4MTQ2OX0.3Jn1fCU66pjICGhUAhrRhYJOWuIUxQYZLzlwGL9w8Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});